on: 
  push:
    branches:
      - 'staging'
name: Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
    - name: Check out repository
      uses: actions/checkout@master
    - name: Upload file via SSH
      uses: appleboy/scp-action@master
      with:
        host: 144.126.143.134
        username: root
        password: "CXX3P7pJQgsne6"
        source: "./*"
        target: "/home/ftpuser/ftp/spero_clinic_front/dev/"


    - name: Remote commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        port: 22
        script: |
          cd /home/ftpuser/ftp/spero_clinic_front/dev
          export NVM_DIR="$HOME/.nvm" 
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 14
          nvm use 14 
          yarn
          yarn build

          /root/.nvm/versions/node/v16.13.0/bin/pm2 start ./pm2/staging.json